CREATE TABLE Bookings (
    BookingID INT PRIMARY KEY,
    FlightID INT,
    CustomerID INT,
    DateID INT,
    RouteID INT,
    SalesChannel NVARCHAR(50),
    TripType NVARCHAR(50),
    PurchaseLead INT,
    LengthOfStay INT,
    FlightHour TIME,
    FlightDay NVARCHAR(50),
    BookingOrigin NVARCHAR(100),
    WantsExtraBaggage BIT,
    WantsPreferredSeat BIT,
    WantsInFlightMeals BIT,
    FlightDuration TIME,
    BookingComplete BIT,
    NumPassengers INT,
    FOREIGN KEY (FlightID) REFERENCES Flight(FlightID),
    FOREIGN KEY (CustomerID) REFERENCES Customer(CustomerID),
    FOREIGN KEY (DateID) REFERENCES Date(DateID),
    FOREIGN KEY (RouteID) REFERENCES Route(RouteID)
);
